[build]
  base = "sham"
  command = "npm run build"
  functions = "netlify/functions"
  publish = "out"

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/profile"
  to = "/.netlify/functions/auth-profile"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/verify"
  to = "/.netlify/functions/auth-verify"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/logout"
  to = "/.netlify/functions/auth-logout"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/users"
  to = "/.netlify/functions/auth-users"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_PATHS = "backend/*,README.md,*.md"
  SECRETS_SCAN_OMIT_KEYS = "CORS_ORIGIN" 